//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelloWebApplication.StudentWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tblStudent", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class tblStudent : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AgeField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        private System.Nullable<int> TotalMarksField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Age {
            get {
                return this.AgeField;
            }
            set {
                if ((object.ReferenceEquals(this.AgeField, value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<int> TotalMarks {
            get {
                return this.TotalMarksField;
            }
            set {
                if ((this.TotalMarksField.Equals(value) != true)) {
                    this.TotalMarksField = value;
                    this.RaisePropertyChanged("TotalMarks");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StudentWebService.StudentServiceSoap")]
    public interface StudentServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetStudentByIDResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStudentByID", ReplyAction="*")]
        HelloWebApplication.StudentWebService.GetStudentByIDResponse GetStudentByID(HelloWebApplication.StudentWebService.GetStudentByIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStudentByID", ReplyAction="*")]
        System.Threading.Tasks.Task<HelloWebApplication.StudentWebService.GetStudentByIDResponse> GetStudentByIDAsync(HelloWebApplication.StudentWebService.GetStudentByIDRequest request);
        
        // CODEGEN: Generating message contract since element name student from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveStudent", ReplyAction="*")]
        HelloWebApplication.StudentWebService.SaveStudentResponse SaveStudent(HelloWebApplication.StudentWebService.SaveStudentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveStudent", ReplyAction="*")]
        System.Threading.Tasks.Task<HelloWebApplication.StudentWebService.SaveStudentResponse> SaveStudentAsync(HelloWebApplication.StudentWebService.SaveStudentRequest request);
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        HelloWebApplication.StudentWebService.HelloWorldResponse HelloWorld(HelloWebApplication.StudentWebService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<HelloWebApplication.StudentWebService.HelloWorldResponse> HelloWorldAsync(HelloWebApplication.StudentWebService.HelloWorldRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStudentByIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStudentByID", Namespace="http://tempuri.org/", Order=0)]
        public HelloWebApplication.StudentWebService.GetStudentByIDRequestBody Body;
        
        public GetStudentByIDRequest() {
        }
        
        public GetStudentByIDRequest(HelloWebApplication.StudentWebService.GetStudentByIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStudentByIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ID;
        
        public GetStudentByIDRequestBody() {
        }
        
        public GetStudentByIDRequestBody(int ID) {
            this.ID = ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStudentByIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStudentByIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public HelloWebApplication.StudentWebService.GetStudentByIDResponseBody Body;
        
        public GetStudentByIDResponse() {
        }
        
        public GetStudentByIDResponse(HelloWebApplication.StudentWebService.GetStudentByIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStudentByIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HelloWebApplication.StudentWebService.tblStudent GetStudentByIDResult;
        
        public GetStudentByIDResponseBody() {
        }
        
        public GetStudentByIDResponseBody(HelloWebApplication.StudentWebService.tblStudent GetStudentByIDResult) {
            this.GetStudentByIDResult = GetStudentByIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveStudentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveStudent", Namespace="http://tempuri.org/", Order=0)]
        public HelloWebApplication.StudentWebService.SaveStudentRequestBody Body;
        
        public SaveStudentRequest() {
        }
        
        public SaveStudentRequest(HelloWebApplication.StudentWebService.SaveStudentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveStudentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HelloWebApplication.StudentWebService.tblStudent student;
        
        public SaveStudentRequestBody() {
        }
        
        public SaveStudentRequestBody(HelloWebApplication.StudentWebService.tblStudent student) {
            this.student = student;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveStudentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveStudentResponse", Namespace="http://tempuri.org/", Order=0)]
        public HelloWebApplication.StudentWebService.SaveStudentResponseBody Body;
        
        public SaveStudentResponse() {
        }
        
        public SaveStudentResponse(HelloWebApplication.StudentWebService.SaveStudentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveStudentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SaveStudentResult;
        
        public SaveStudentResponseBody() {
        }
        
        public SaveStudentResponseBody(bool SaveStudentResult) {
            this.SaveStudentResult = SaveStudentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public HelloWebApplication.StudentWebService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(HelloWebApplication.StudentWebService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public HelloWebApplication.StudentWebService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(HelloWebApplication.StudentWebService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StudentServiceSoapChannel : HelloWebApplication.StudentWebService.StudentServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StudentServiceSoapClient : System.ServiceModel.ClientBase<HelloWebApplication.StudentWebService.StudentServiceSoap>, HelloWebApplication.StudentWebService.StudentServiceSoap {
        
        public StudentServiceSoapClient() {
        }
        
        public StudentServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StudentServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HelloWebApplication.StudentWebService.GetStudentByIDResponse HelloWebApplication.StudentWebService.StudentServiceSoap.GetStudentByID(HelloWebApplication.StudentWebService.GetStudentByIDRequest request) {
            return base.Channel.GetStudentByID(request);
        }
        
        public HelloWebApplication.StudentWebService.tblStudent GetStudentByID(int ID) {
            HelloWebApplication.StudentWebService.GetStudentByIDRequest inValue = new HelloWebApplication.StudentWebService.GetStudentByIDRequest();
            inValue.Body = new HelloWebApplication.StudentWebService.GetStudentByIDRequestBody();
            inValue.Body.ID = ID;
            HelloWebApplication.StudentWebService.GetStudentByIDResponse retVal = ((HelloWebApplication.StudentWebService.StudentServiceSoap)(this)).GetStudentByID(inValue);
            return retVal.Body.GetStudentByIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HelloWebApplication.StudentWebService.GetStudentByIDResponse> HelloWebApplication.StudentWebService.StudentServiceSoap.GetStudentByIDAsync(HelloWebApplication.StudentWebService.GetStudentByIDRequest request) {
            return base.Channel.GetStudentByIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<HelloWebApplication.StudentWebService.GetStudentByIDResponse> GetStudentByIDAsync(int ID) {
            HelloWebApplication.StudentWebService.GetStudentByIDRequest inValue = new HelloWebApplication.StudentWebService.GetStudentByIDRequest();
            inValue.Body = new HelloWebApplication.StudentWebService.GetStudentByIDRequestBody();
            inValue.Body.ID = ID;
            return ((HelloWebApplication.StudentWebService.StudentServiceSoap)(this)).GetStudentByIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HelloWebApplication.StudentWebService.SaveStudentResponse HelloWebApplication.StudentWebService.StudentServiceSoap.SaveStudent(HelloWebApplication.StudentWebService.SaveStudentRequest request) {
            return base.Channel.SaveStudent(request);
        }
        
        public bool SaveStudent(HelloWebApplication.StudentWebService.tblStudent student) {
            HelloWebApplication.StudentWebService.SaveStudentRequest inValue = new HelloWebApplication.StudentWebService.SaveStudentRequest();
            inValue.Body = new HelloWebApplication.StudentWebService.SaveStudentRequestBody();
            inValue.Body.student = student;
            HelloWebApplication.StudentWebService.SaveStudentResponse retVal = ((HelloWebApplication.StudentWebService.StudentServiceSoap)(this)).SaveStudent(inValue);
            return retVal.Body.SaveStudentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HelloWebApplication.StudentWebService.SaveStudentResponse> HelloWebApplication.StudentWebService.StudentServiceSoap.SaveStudentAsync(HelloWebApplication.StudentWebService.SaveStudentRequest request) {
            return base.Channel.SaveStudentAsync(request);
        }
        
        public System.Threading.Tasks.Task<HelloWebApplication.StudentWebService.SaveStudentResponse> SaveStudentAsync(HelloWebApplication.StudentWebService.tblStudent student) {
            HelloWebApplication.StudentWebService.SaveStudentRequest inValue = new HelloWebApplication.StudentWebService.SaveStudentRequest();
            inValue.Body = new HelloWebApplication.StudentWebService.SaveStudentRequestBody();
            inValue.Body.student = student;
            return ((HelloWebApplication.StudentWebService.StudentServiceSoap)(this)).SaveStudentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HelloWebApplication.StudentWebService.HelloWorldResponse HelloWebApplication.StudentWebService.StudentServiceSoap.HelloWorld(HelloWebApplication.StudentWebService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            HelloWebApplication.StudentWebService.HelloWorldRequest inValue = new HelloWebApplication.StudentWebService.HelloWorldRequest();
            inValue.Body = new HelloWebApplication.StudentWebService.HelloWorldRequestBody();
            HelloWebApplication.StudentWebService.HelloWorldResponse retVal = ((HelloWebApplication.StudentWebService.StudentServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HelloWebApplication.StudentWebService.HelloWorldResponse> HelloWebApplication.StudentWebService.StudentServiceSoap.HelloWorldAsync(HelloWebApplication.StudentWebService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<HelloWebApplication.StudentWebService.HelloWorldResponse> HelloWorldAsync() {
            HelloWebApplication.StudentWebService.HelloWorldRequest inValue = new HelloWebApplication.StudentWebService.HelloWorldRequest();
            inValue.Body = new HelloWebApplication.StudentWebService.HelloWorldRequestBody();
            return ((HelloWebApplication.StudentWebService.StudentServiceSoap)(this)).HelloWorldAsync(inValue);
        }
    }
}
